title: El Capitan
author: Ziraddin Gulumjanli
copyright: "2026"
logo: cover.png

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/ziraddingulumjanly/El-Capitan
  branch: main

html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false
  favicon: ""

launch_buttons:
  notebook_interface: "jupyterlab"

# Add the configuration below:
sphinx:
  config:
    html_show_copyright: true
    html_theme_options:
      extra_navbar: ""
      # This explicitly activates the text title below your cover image
      logo_title: "El Capitan" 

exclude_patterns:
  - README.md
  - README_JUPYTER_BOOK_SETUP.md
  - data/**
  - models/**
  - outputs/**
  - .github/**
