title: El Capitan 
author: Ziraddin Gulumjanli
copyright: "2026"
logo: cover.png

execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/ziraddingulumjanly/El-Capitan
  branch: main

html:
  use_repository_button: true
  use_issues_button: false
  use_edit_page_button: false

launch_buttons:
  notebook_interface: "jupyterlab"

sphinx:
  config:
    html_show_copyright: true
    html_theme_options:
      logo:
        text: "El Capitan"

      extra_footer: |
        <p>
          <br>
          <a href="https://github.com/ziraddingulumjanly">GitHub Repo</a>
          |
          <a href="https://ziraddingulumjanly.github.io/MLBook/intro.html">Machine Learning Projects</a>
        </p>

exclude_patterns:
  - README.md
  - README_JUPYTER_BOOK_SETUP.md
  - data/**
  - models/**
  - outputs/**
  - .github/**